### ISSUE TITLE
error with running

### ISSUE THREAD

**Issue by levimoore1992** [schoolofcode-me/price-of-chair#4]
ImportError: cannot import name user_blueprint

its the same with the other views

**Comment by jslvtr** [comment]
Hey @levimoore1992 this is probably an issue with your code or the way the project has been set up (folders and folder structure). If you can ask a question in the appropriate Course Q&A we'll help you there.

The issues section of this project is for problems with the code itself (i.e. bugs) or for suggestions for improvement.
